import java.util.ArrayList;
import java.util.List;

/**
 * 
 * Input: a String and list of concept with type and their intervals.
 * Output: a new String with all concept are 
 * warpped with tags according to their types. 
 * 
 * @author jingtian
 *
 */
public class Main {

	public static void main(String[] args){

		//get from module 1.
		String str = "Obama visited FaceBook headquarters: http://bit.ly/xyz @elversatile"; //aNewsFeed
		System.out.println("Test Input: " + str + "\n");

		//generated by module 2.
		List<InputDataUnit> input = new ArrayList<InputDataUnit>();	
		input.add(new InputDataUnit(14, 22, "Entity", new Entity()));
		input.add(new InputDataUnit(0, 5, "Entity", new Entity()));
		input.add(new InputDataUnit(56, 67, "Twitter username",  new TwitterUserName()));
		input.add(new InputDataUnit(37, 54, "Link",  new Link()));

		System.out.println("Data from Module 2.");
		for(InputDataUnit u : input){
			System.out.println(String.format("%d - %d: \"%s\"", u.getStart(), u.getEnd(), str.substring(u.getStart(), u.getEnd())+ " : "+ u.getType()));
		}
		System.out.println("End of data from Module 2.");

		//generate map
		System.out.println("\nBuilding mapping between concept type and Class name.");

		TypeClassMap map = new TypeClassMap();
		String k = ""; String v = "";
		k = "Twitter username"; v = "TwitterUserName";
		map.addToMap(k, v);
		System.out.println(String.format("Add type: \"%s\", class: \"%s\"", k, v));
		k = "Entity"; v = "Entity";
		map.addToMap(k, v);
		System.out.println(String.format("Add type: \"%s\", class: \"%s\"", k, v));
		k = "Link"; v = "Link";
		map.addToMap(k, v);
		System.out.println(String.format("Add type: \"%s\", class: \"%s\"", k, v));

		/**
		 * Test 1: example
		 */
		System.out.println("\n********************\n*****Test 1 : example of the assignment*****");
		Module3 instance = new Module3(str, input, map);
		//output to the console
		System.out.println("Results: \n" + instance.getWrappedNewFeed());


		/**
		 * Test 2: remove a type
		 */
		System.out.println("\n********************\n*****Test 2: remove a type*****");
		k = "Entity";
		map.removeType(k);
		System.out.println(String.format("removed type \"%s\"", k));

		Module3 instance2 = new Module3(str, input, map);

		//output to the console
		System.out.println("Results: \n" + instance2.getWrappedNewFeed());

		/**
		 * Test 3: add a type
		 */
		System.out.println("\n********************\n*****Test 3: add a new type*****");
		k = "Entity"; v = "Entity";
		map.addToMap(k, v);
		System.out.println(String.format("Assume we add a NEW type \"%s\" to a NEW Class \"%s\"", k, v));

		Module3 instance3 = new Module3(str, input, map);
		//output to the console
		System.out.println("Results: \n" + instance3.getWrappedNewFeed());


		/**
		 * Test 4: wrong class name.
		 */
		System.out.println("\n********************\n*****Test 4: wrong class name*****");
		k = "Link"; v = "link";
		map.addToMap(k, v);
		System.out.println(String.format("Assume we map type \"%s\" to a non-extist Class \"%s\"", k, v));

		Module3 instance4 = new Module3(str, input, map);		
		//output to the console
		System.out.println("Results: \n" + instance4.getWrappedNewFeed());


		/**
		 * Test 5: wrong input, overlapped tagging.
		 */
		System.out.println("\n********************\n*****Test 5: wrong input, overlapped tagging*****");
		map.addToMap("Link", "Link"); // recover "Link"
		map.removeType("entity"); 
		map.addToMap("Entity", "Entity");
		input.add(new InputDataUnit(18, 26, "Entity"));
		Module3 instance5 = new Module3(str, input, map);
		//output to the console
		System.out.println("Results: \n" + instance5.getWrappedNewFeed());

	}



}
