import java.util.ArrayList;
import java.util.List;

/**
 * 
 * Input: a String and list of concept with type and their intervals.
 * Output: a new String with all concept are 
 * warpped with tags according to their types. 
 * 
 * @author jingtian
 *
 */
public class Main {

	public static void main(String[] args){
		
		//get from module 1.
		String str = "Obama visited FaceBook headquarters: http://bit.ly/xyz @elversatile"; //aNewsFeed
		System.out.println("Test Input: \n" + str + "\n");

		//generated by module 2.
		// out of range tagging, overlap tagging, wrong type, null value should be prevented in module2.
		List<InputDataUnit> input = new ArrayList<InputDataUnit>();	
		input.add(new InputDataUnit(14, 22, "Entity", new Entity()));
		input.add(new InputDataUnit(0, 5, "Entity", new Entity()));
		input.add(new InputDataUnit(56, 67, "Twitter username",  new TwitterUserName()));
		input.add(new InputDataUnit(37, 54, "Link",  new Link()));

		System.out.println("Data from Module 2.");
		for(InputDataUnit u : input){
			System.out.println(String.format("%d - %d: \"%s\"", u.getStart(), u.getEnd(), str.substring(u.getStart(), u.getEnd())+ " : "+ u.getType()));
		}
		System.out.println("End of data from Module 2.");

		Module3 instance = new Module3(str, input);
		//output to the console
		System.out.println("\nResults: \n" + instance.getWrappedNewFeed());


	}



}
